#!/usr/bin/env sh

# Run type-check
echo "Running typecheck..."
pnpm typecheck || exit 1

# Run lint
echo "Running lint..."
pnpm lint:check || exit 1

# Run lint-staged (format and stage changes)
echo "Running formatter..."
pnpm lint-staged